spring:
  cloud:
    stream:
      default-binder: solaceBroker
      bindings:
        input:
          destination: TEMPS.Q
          group: PROCESSOR
        output:
          destination: sensor/temperature/celsius
      binders:
        solaceBroker:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: -1
                reconnectRetries: -1
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: sensor/temperature/fahrenheit
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO
    
server:
  port: 8094
